name: criterion-tracker
services:
  - name: web
    source_dir: /
    github:
      repo: tedrubin80/criterion-tracker
      branch: main
      deploy_on_push: true
    run_command: gunicorn app:app --bind 0.0.0.0:8080 --worker-tmp-dir /dev/shm --timeout 120 --workers 2
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health
    routes:
      - path: /
    env:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: change-this-to-a-random-string
        type: SECRET
      - key: DATABASE_PATH
        value: /tmp/criterion_releases.db
